/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/model.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group>
          <primitive object={nodes.Rig_Hips} />
          <skinnedMesh geometry={nodes.Solus_Knight.geometry} material={materials.Solus_Knight} skeleton={nodes.Solus_Knight.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model.glb')
